spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mymemdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: test
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none

  queries:
    roles-query: SELECT u.email, r.role from app_user u inner join user_roles ur on(u.id=ur.user_id) inner join role r on(ur.roles_id=r.id) where u.email=?;
    users-query: SELECT email, password, active FROM app_user where email=?;

upload:
  work-dir: work